### ISSUE TITLE
CLI output improvements

### ISSUE THREAD

**Issue by lazio** [Halo-Lab/kickin#2]
Hey, I like the CLI output it's lovely, a few improvements I can suggest: 
1. Can we have a progress bar when installing dependencies? not sure it's doable, but maybe you can have a look? 
2. Can we have a suggestion of doing `cd [project_name]` after setup is completed but before `npm start`? Because when I see suggestion to do `npm start` I'm, like, immidiately doing it, but I'm not in my project folder yet, so it doesn't work

**Comment by Kapelianovych** [comment]
Hello, thank you for suggesting ideas! They was implemented in [0.2.0](https://github.com/Halo-Lab/kickin/releases/tag/v0.2.0) release.
